EXP-204 feat(Login): update can access login rule
pagarme/pilot pull request #1741
Opened 2020-09-15 14:00 UTC by allangrds

## Contexto

## Checklist
- [ ] Itens

## Issues linkadas
- [ ] Resolves #

## Screenshots

### Layout:
[insira o screenshot aqui]

### Preview:
[insira o screenshot aqui]

## Notas de deploy

## Como testar?

**Novos scripts**:

- `script` : detalhes do script

**Novas dependências**:

- `dependency` : detalhes da dependência

**Novas dependências de desenvolvedor**:

- `dependency` : detalhes da dependência

2020-09-16 19:49 UTC, diegodsgarcia requested changes

2020-09-16 19:49 UTC, diegodsgarcia commented on packages/pilot/src/pages/Account/actions/epic.js
> +      if (!hasDashboardAccess(company)) {
Aqui o certo deveria passar o client em vez da company

2020-09-16 20:00 UTC, diegodsgarcia requested changes

2020-09-16 20:00 UTC, diegodsgarcia commented on packages/pilot/src/pages/Account/actions/epic.js
> +      if (!hasDashboardAccess(company)) {
Aqui o certo não seria o `client` em vez da `company`? 🤔

2020-09-16 20:07 UTC, diegodsgarcia commented on packages/pilot/src/pages/Account/actions/epic.js
> +const hasDashboardAccess = company => path(['client', 'authentication', 'allow_dashboard_login'], company)
O certo não seria pegar do caminho `company. capabilities.allow_dashboard_login`?:think:

2020-09-17 15:06 UTC, vagnervst commented on packages/pilot/src/pages/Account/actions/epic.js
> +const hasDashboardAccess = company => path(['company', 'capabilities', 'allow_dashboard_login'], company)
só ajustar a função pra puxar a capability da company:

```suggestion
const hasDashboardAccess = path(['capabilities', 'allow_dashboard_login'])
```

2020-09-17 16:27 UTC, diegodsgarcia approved these changes

2020-09-17 19:31 UTC, vagnervst approved these changes

2020-09-18 12:07 UTC, merged