[EXP-748] Extrato - mapear fee collections do tipo contract_adjustment
pagarme/pilot pull request #1867
Opened 2021-05-19 17:24 UTC by Hrfreire

## Contexto
Este PR adiciona layout específico para o liquidation arrangement, na tabela de extrato.

## Checklist
- [x] O cockpit deve estar mapeando corretamente os fee_collections do tipo contract_adjustement
- [x] As linhas do novo tipo de fee collection mapeado deve ser exibidas conforme o protótipo
- [x] Deve existir a tooltip com as informações prototipadas
- [ ] O link saiba mais da tooltip deve abrir o modal `ExternalContractAdjustment` (Não foi feito pois não sabemos se esse botão vai realmente existir, devido a problemas com o componente Tooltip do Former Kit)
- [x] O link veja o lançamento deve redirecionar para a rota  `/settlement/id_recebedor?liquidation_arrangiment_id=<id do liquidation_arrangiment_id informado na fee collection>`

## Screenshots
![image](https://user-images.githubusercontent.com/5042920/118856713-a0b4f980-b8ad-11eb-9cc0-5ab32e996a93.png)

### Layout:
![image](https://user-images.githubusercontent.com/5042920/118856452-5764aa00-b8ad-11eb-8ff4-c8f31b740094.png)

## Como testar?
1. - Nesta linha: https://github.com/pagarme/pilot/blob/71ed2756b8bf7e4277746b0ac067ebf2f56f9d4d/packages/cockpit/src/balance/operations/buildRequest.js#L58-L59
mockar o seguinte retorno:
<details>
 <summary>Mock</summary>

```js
return Promise.resolve(formatOperationsRows(
  [
    {
      "object": "balance_operation",
      "id": 16194935,
      "status": "available",
      "balance_amount": 0,
      "balance_old_amount": null,
      "type": "payable",
      "amount": 2500,
      "fee": 119,
      "date_created": "2021-03-15T17:25:47.716Z",
      "movement_object": {
        "object": "payable",
        "id": 14593882,
        "status": "paid",
        "amount": 2500,
        "fee": 119,
        "anticipation_fee": 0,
        "fraud_coverage_fee": 0,
        "installment": null,
        "transaction_id": 11722328,
        "split_rule_id": "sr_ckmauxpye0uhl0h9tneckr9ie",
        "bulk_anticipation_id": null,
        "anticipation_id": null,
        "recipient_id": "re_cj47hn60h008kw16dwim8qm89",
        "originator_model": null,
        "originator_model_id": null,
        "payment_date": "2021-03-15T03:00:00.684Z",
        "original_payment_date": null,
        "type": "credit",
        "payment_method": "pix",
        "accrual_date": null,
        "date_created": "2021-03-15T17:25:47.705Z",
        "liquidation_arrangement_id": null
      }
    },
    {
      "object": "balance_operation",
      "id": 1,
      "status": "available",
      "balance_amount": null,
      "balance_old_amount": null,
      "type": 'fee_collection',
      "amount": 100,
      "fee": null,
      "date_created": "2021-05-04T19:47:49.319Z",
      "movement_object": {
        "object": "fee_collection",
        "id": "fc_123",
        "status": "available",
        "type": "contract_adjustment",
        "description": "Ajuste residual de contrato de liquidação",
        "payment_date": "2021-05-04T00:00:00.000Z",
        "amount": 100,
        "recipient_id": "re_123",
        "date_created": "2021-05-04T19:49:23.607Z",
        "object_id": "la_123",
        "object_type": "liquidation_arrangement"
      }
    }
  ]
 ))
```
</details>

2. Buildar cockpit com esse mock.

3. Rodar a pilot, ir no extrato e ver se o layout aparece corretamente.

4. Verificar se a url com título "Veja o lançamento" está seguindo o padrão descrito acima.

2021-05-20 18:49 UTC, diegodsgarcia approved these changes
LGTM

2021-05-20 21:44 UTC, LucasRichter requested changes

2021-05-20 21:44 UTC, LucasRichter commented on packages/pilot/src/components/Operations/operationsTableColumns.js
> +        <Link to={`/settlement/${recipientId}?liquidation_arrangiment_id=${liquidationArrangementId}`}>
Essa url leva pra página de listagem de liquidações?

2021-05-20 21:51 UTC, Hrfreire commented on packages/pilot/src/components/Operations/operationsTableColumns.js
> +        <Link to={`/settlement/${recipientId}?liquidation_arrangiment_id=${liquidationArrangementId}`}>
Isso, era a url que estava definida na tarefa do Jira:
![image](https://user-images.githubusercontent.com/5042920/119053398-65452880-b99c-11eb-9b66-651e68902a73.png)

2021-05-20 21:58 UTC, LucasRichter commented on packages/pilot/src/components/Operations/operationsTableColumns.js
> +        <Link to={`/settlement/${recipientId}?liquidation_arrangiment_id=${liquidationArrangementId}`}>
Estranho. A tarefa de página de settlemnts diz pra pegar o recipientId da company.

2021-05-21 17:06 UTC, LucasRichter commented on packages/pilot/src/components/Operations/operationsTableColumns.js
> +        <Link to={`/settlement/${recipientId}?liquidation_arrangiment_id=${liquidationArrangementId}`}>
Acho que vale trocar a rota para `/settlements` para manter o padrão das outras rotas

2021-05-21 20:24 UTC, diegodsgarcia approved these changes

2021-05-26 20:36 UTC, ThaisRobba commented
O run-sonar-analysis está marcado como tendo sido cancelado, era isso mesmo ou é precisa rerodar?

2021-05-26 23:59 UTC, Hrfreire commented
> O run-sonar-analysis está marcado como tendo sido cancelado, era isso mesmo ou é precisa rerodar?

Creio que foi algum problema do circleCI mesmo. Não acho que foi cancelado manualmente. Já rodei novamente.

2021-05-31 19:17 UTC, ThaisRobba approved these changes
Parece show! Uma coisa que achei que o texto pode ficar confuso de falar "Saiba mais no card A Receber acima", sendo que é uma aba do card geral. Mas não afeta esse pr.

2021-05-31 19:43 UTC, merged

2021-05-31 19:44 UTC, Hrfreire commented
> Parece show! Uma coisa que achei que o texto pode ficar confuso de falar "Saiba mais no card A Receber acima", sendo que é uma aba do card geral. Mas não afeta esse pr.

É, foi o texto passado pelos designers do outro time, podemos conversar se vale a pena mudar.