EXP-749: Criar pagina de liquidações
pagarme/pilot pull request #1872
Opened 2021-05-24 18:07 UTC by LucasRichter

## Contexto
Criação da página de listagem de Liquidações por recipientId.  [Link para o card](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=185&projectKey=EXP&modal=detail&selectedIssue=EXP-749)

## Screenshots

### Layout:
[Figma](https://www.figma.com/file/RNqvkhkAvAen1Vq4fee820/Pilot?node-id=4483%3A39) 
### Preview:
![localhost_3000_](https://user-images.githubusercontent.com/14004196/119388215-5910e200-bca0-11eb-92eb-696567327c80.png)
![localhost_3000_ (1)](https://user-images.githubusercontent.com/14004196/119389182-a477c000-bca1-11eb-8cdb-57c4f19809a2.png)

*Nota: o icon de Liquidações ainda será mudado

## Como testar?
- Checkout nessa branch
- Rodar com `yarn start`
- Verificar se a opção está presente no menu a esquerda
- Verificar se a tela de liquidações está sendo renderizada corretamente ao clicar no menu a esquerda
- Atualizar `packages/pilot/src/pages/Settlements/SettlementsPage.js:102`  para usar arquivo mock.js e descomentar a `packages/pilot/src/pages/Settlements/SettlementsPage.js:32` 
- Verificar se ao aplicar os filtros, a URL atualiza corretamente
- Verificar se ao limpar o filtro, a URL atualizar para os dados default (Data 1 semana)

2021-05-24 18:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-24 18:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-24 18:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-24 18:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-24 18:37 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/tableColumns.js
> +    renderer: renderStatusLegend(t),
Vale a pena verificarmos se isso está incluindo a tooltip

2021-05-24 18:44 UTC, ThaisRobba commented on packages/pilot/src/pages/LoggedArea/routes.js
> +    hidden: false,
Essa flag é necessária?

2021-05-24 19:47 UTC, ThaisRobba requested changes

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/Filter/index.js
> +      start: isMomentPropValidation,
- [ ] Substituir `isMomentPropValidation` de pacote externo por versão local

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/Filter/index.js
> +      start: isMomentPropValidation,
- [ ] Adicionar `.required` pros props necessários de data

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/Filter/style.css
> +  padding: 32px 24px;
Aqui vale a pena olhar se podemos puxar valores padrão da folha de estilo de `spacing`

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    offset: 1,
Acho que aqui vale definir como constantes os valores pra ficar claro o que são, algo como `const itemsPerPage = 15` e `const initialPage = 1`?

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +  return initialState
Eu mudaria para ficar afirmativo ao invés de negativo, algo como:

```javascript
if (query.start_date && query.end_date) {
  return initialState
}

const today = moment()
const start = moment().subtract(7, 'days')
return {
     ...initialState,
     end_date: today.format('DD-MM-YYYY'),
     start_date: start.format('DD-MM-YYYY'),
 }
```

O que acha?

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    await sleeper(1000, recipientId)
- [ ] Substituir sleeper por request

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    onFilterChange('offset', +offset)
Não sei se aqui vale usar um `parseInt`, acho que não tem problema fazer com `+` mas o parseToInt é mais explícito

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    onFilterChange('offset', +offset)
algo como `parseInt(offset, 10)`

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    onFilterChange('offset', +offset)
O que você acha?

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                        currentPage={+filters.offset}
Acho que vale o mesmo comentário de cima do parseInt

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                    currentPage={+filters.offset}
Aqui também do parseInt

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                        totalPages={1}
Aqui a gente vai precisar popular a partir do que vier da API, né?

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                    totalPages={1}
Mesmo do outro

2021-05-24 19:47 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/tableColumns.js
> +import renderStatusLegend from '../../containers/TransactionsList/renderStatusLegend'
Acho que vale promover pra fora do TransactionsList visto que estamos usando em outros lugares. Talvez um componente `StatusLegend`?

2021-05-24 19:49 UTC, ThaisRobba requested changes

2021-05-24 19:49 UTC, ThaisRobba commented on packages/pilot/src/containers/TransactionsList/index.js
> +export const buildEmptyState = t => (
Acho que vale promover esse carinha pra componente também :)

2021-05-24 19:58 UTC, ThaisRobba requested changes

2021-05-24 19:58 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    onFilterChange('offset', +offset)
Faria até uma variável mais pra raíz do componente, para garantir que os elementos de paginação sempre estivessem sincronizados

2021-05-25 16:32 UTC, LucasRichter commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                    currentPage={+filters.offset}
Mas pq o parseInt se o `+` faz o mesmo?

2021-05-25 16:32 UTC, LucasRichter commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                        totalPages={1}
sim

2021-05-25 16:34 UTC, LucasRichter commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    offset: 1,
Não sei se vale pq é usado só aqui. Em nenhum momento a gente reutiliza esses valores.

2021-05-26 14:26 UTC, ThaisRobba commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +                        totalPages={1}
Podemos mapear então pra um valor com um useState, porque depois é só dar o setState da variável :)

2021-05-27 19:55 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 0d211b5b7f4e2d9970821bc621558da41ec9b5bf
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:55 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 0d211b5b7f4e2d9970821bc621558da41ec9b5bf
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:55 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 0d211b5b7f4e2d9970821bc621558da41ec9b5bf
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:55 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 0d211b5b7f4e2d9970821bc621558da41ec9b5bf
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 14e9ddde8265326874c60148e11c146158d85c4a
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 14e9ddde8265326874c60148e11c146158d85c4a
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 14e9ddde8265326874c60148e11c146158d85c4a
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 14e9ddde8265326874c60148e11c146158d85c4a
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:04 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 5c39baea869889de2bcf7e2a57baeee28d6b9c6c
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:04 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 5c39baea869889de2bcf7e2a57baeee28d6b9c6c
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:04 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 5c39baea869889de2bcf7e2a57baeee28d6b9c6c
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:04 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 5c39baea869889de2bcf7e2a57baeee28d6b9c6c
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:24 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:24 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:24 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-27 20:24 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-28 13:23 UTC, Hrfreire reviewed
Tive esse erro ao testar:

![image](https://user-images.githubusercontent.com/5042920/119990221-7692c400-bf9e-11eb-9fef-065c35cb8ffe.png)

As datas estão formatadas só como DD/MM/YYYY
 
 Quando mudei as datas na url, pra bater com ISOString, voltou a funcionar.

2021-05-28 13:23 UTC, Hrfreire commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +    onFilterChange('offset', +offset)
Concordo, acho que parseInt fica mais claro.

2021-05-28 13:26 UTC, Hrfreire commented
Um outro detalhe, tem alguns warning do proptypes que acho que seria bom arrumar

2021-05-28 13:30 UTC, Hrfreire commented
Quando tentei usar os filtros de data, aparentemente elas não foram enviadas:

Filtrei datas de 2020 e mesmo assim ele mostrou coisa mais atual e também olhando a url dá pra ver que nenhuma data foi enviada.
![image](https://user-images.githubusercontent.com/5042920/119991245-a1c9e300-bf9f-11eb-9bd6-d0fb8a8cabee.png)

2021-05-28 13:35 UTC, Hrfreire commented
Acho que um comportamento não esperado tá acontecendo: Ao mudar a data ou ao preencher o campo de pesquisa, ele já está enviando requisições de busca. Creio que isso só deveria acontecer ao clicar no botão filtrar.

2021-05-28 13:40 UTC, Hrfreire commented
Ao entrar pela url: (padrão que vai vir do link que fica no extrato)
http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?liquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn

Tá sendo inserido automaticamente as datas como filtro, ficando assim:
http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?count=15&offset=1&%3Fliquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn&payment_date_end=28-05-2021&payment_date_start=21-05-2021

Acho que é um problema porque caso o LA não esteja nesse range, ele não vai aparecer.

2021-05-28 18:39 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 4b6644f1acbeaacc7bcfae45635e2eb590ed24fe
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-28 18:39 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 4b6644f1acbeaacc7bcfae45635e2eb590ed24fe
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-28 18:39 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 4b6644f1acbeaacc7bcfae45635e2eb590ed24fe
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-28 18:39 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 4b6644f1acbeaacc7bcfae45635e2eb590ed24fe
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-05-28 20:40 UTC, diegodsgarcia reviewed
Acho que no final vale cria um teste bem básico por menos renderizando o componente mockado com seus dados

2021-05-28 20:45 UTC, diegodsgarcia reviewed
Acho legal tbm evitar commits desse tipo `fix pr issues`, pois é muito generico e não descreve exatamente as modificações caso a gente precise consultar no futuro. Talvez vale faze rebase mesmo com os commits ja criado.

2021-06-01 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 19:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 20:10 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 20:10 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 20:10 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-01 20:10 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 14:08 UTC, Hrfreire commented
> Ao entrar pela url: (padrão que vai vir do link que fica no extrato)
> http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?liquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn
> 
> Tá sendo inserido automaticamente as datas como filtro, ficando assim:
> http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?count=15&offset=1&%3Fliquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn&payment_date_end=28-05-2021&payment_date_start=21-05-2021
> 
> Acho que é um problema porque caso o LA não esteja nesse range, ele não vai aparecer.

Esse comportamento continua acontecendo.

2021-06-02 14:15 UTC, Hrfreire reviewed
Uma outra coisa:
1. - Quando o `liquidation_arrangement_id` já vem na rota, ele não tá preenchendo esse id no campo de busca. para o usuário entender que está buscando por esse filtro. Inclusive, se o usuário alterar os filtros, o `liquidation_arrangement_id` continua sendo usado como filtro e usuário nem vai saber.

2021-06-02 14:15 UTC, Hrfreire commented on packages/pilot/src/pages/Account/actions/epic.js
> +      hasExternalContract: true,
aqui ele devia usar os results pra setar essa flag, certo?

2021-06-02 14:21 UTC, Hrfreire commented on packages/pilot/src/pages/Account/actions/epic.js
> +      hasExternalContract: true,
Na verdade, eu acredito que esse epic não tá sendo nem usado. Procurei no codigo onde a action `getExternalContract` estaria sendo chamada, e não encontrei. Todos os lugares que vi ele tá pegando essa flag direto da company.

2021-06-02 14:21 UTC, rsmelo commented on packages/pilot/src/containers/StatusLegend/style.css
> +    margin-left: 8px;
aqui pode usar --spacing-tiny

2021-06-02 14:22 UTC, rsmelo commented on packages/pilot/src/containers/StatusLegend/style.css
> +    color: #ea5673;
talvez criar uma variavel pra essa cor caso use em mais locais

2021-06-02 14:22 UTC, Hrfreire commented
Só pra a gente não esquecer:

- Tem que remover uns console.log
- Tem que trocar created_at por payment_date na tabela

2021-06-02 14:23 UTC, rsmelo commented on packages/pilot/src/locales/pt/translations.json
> +      "created_date": "Data",
atualizar essa label aqui, tá como created_at mas vimos que é payment_date

2021-06-02 14:25 UTC, rsmelo commented on packages/pilot/src/pages/Account/actions/epic.js
> +    console.log(results)
ficou um console.log perdido aqui

2021-06-02 14:27 UTC, rsmelo commented on packages/pilot/src/pages/LoggedArea/dynamicImports.js
> +  /* webpackChunkName: "payment-links" */ '../Settlements'
```suggestion
  /* webpackChunkName: "settlements" */ '../Settlements'
```

essa notação define o nome do chunk

2021-06-02 14:27 UTC, rsmelo commented on packages/pilot/src/pages/LoggedArea/index.js
> +  console.log(company.hasExternalContract)
console.log perdido aqui

2021-06-02 14:49 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 14:49 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 14:49 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 14:49 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:38 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:38 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:38 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:38 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:52 UTC, LucasRichter commented on packages/pilot/src/containers/StatusLegend/style.css
> +    color: #ea5673;
só usa nesse local

2021-06-02 16:56 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e45d6bc69133764627dbf160c2628ab6f7d858e9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:56 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e45d6bc69133764627dbf160c2628ab6f7d858e9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:56 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e45d6bc69133764627dbf160c2628ab6f7d858e9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 16:56 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e45d6bc69133764627dbf160c2628ab6f7d858e9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 19:25 UTC, Hrfreire requested changes

2021-06-02 19:25 UTC, Hrfreire commented on packages/pilot/src/pages/Account/actions/epic.js
> +          hasExternalContract: results.contracts.lenght > 0,
```suggestion
          hasExternalContract: results.contracts.length > 0,
```

2021-06-02 19:26 UTC, Hrfreire commented
> Uma outra coisa:
> 
> 1. * Quando o `liquidation_arrangement_id` já vem na rota, ele não tá preenchendo esse id no campo de busca. para o usuário entender que está buscando por esse filtro. Inclusive, se o usuário alterar os filtros, o `liquidation_arrangement_id` continua sendo usado como filtro e usuário nem vai saber.

esse comportamento continua acontecendo.

2021-06-02 19:26 UTC, Hrfreire commented
> Ao entrar pela url: (padrão que vai vir do link que fica no extrato)
> http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?liquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn
> 
> Tá sendo inserido automaticamente as datas como filtro, ficando assim:
> http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?count=15&offset=1&%3Fliquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn&payment_date_end=28-05-2021&payment_date_start=21-05-2021
> 
> Acho que é um problema porque caso o LA não esteja nesse range, ele não vai aparecer.

Esse comportamento continua acontecendo.

2021-06-02 19:33 UTC, Hrfreire commented
Quando o cara vem da url: 
http://localhost:3000/#/settlements/re_ckhl4tvgw07uu0m9tpmw6kt01?liquidation_arrangment_id=la_ckou6pkigbhns0ojugesjslyn

Que é a url que vem do extrato, ele tá inserindo as datas na busca, o que faz com que a LA pesquisada não apareça.

![image](https://user-images.githubusercontent.com/5042920/120541409-39746a80-c3c0-11eb-83aa-84bb6e6b7c4e.png)

Creio que nesse caso, tem que fazer a busca só pelo liquidation_arrangment_id, porque o usuário não vai perceber que não apareceu por causa das datas.

2021-06-02 19:34 UTC, Hrfreire commented
Continua dando uns erros de proptypes que era bom corrigir

![image](https://user-images.githubusercontent.com/5042920/120541547-66c11880-c3c0-11eb-9149-fc805d7000e9.png)

2021-06-02 20:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e6656c730b2a51bcf741bc7b914f065d4defe338
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 20:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e6656c730b2a51bcf741bc7b914f065d4defe338
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 20:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e6656c730b2a51bcf741bc7b914f065d4defe338
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-02 20:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: e6656c730b2a51bcf741bc7b914f065d4defe338
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-03 13:53 UTC, diegodsgarcia commented on packages/pilot/package.json
> +    "start": "env REACT_APP_API_ENVIRONMENT=live react-scripts start",
Será que aqui não é melhor nos criar um comando novo? Pois dessa forma não teremos mais acesso ao ambiente sandbox da API.

2021-06-03 13:53 UTC, diegodsgarcia commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +      currentPage={filters.offset}
Aqui o currentPage espera um `number` e na queryString esta vindo uma string. Acho que vale converter isso na função `buildInitialState`, pra evitar esses erros de tipagem

2021-06-03 17:06 UTC, diegodsgarcia commented
Pode ficar como task secundário mas agora fazendo direto na page eu percebi que vai ficar mais dificil fazer os testes de componente no jest (pois compõe do estado do redux), e também cria um storie no storybook. Com isso perdemos também os testes no percy.
Talvez criando um mock do redux funcione, precisamos debater melhor a estrategia que iremos fazer para isso

2021-06-03 17:20 UTC, diegodsgarcia commented on packages/pilot/src/pages/Account/actions/epic.js
> +          hasExternalContract: results.contracts.length > 0 || true,
Aqui confesso que não entendi.... Sempre vai dar `true` essa condição, é isso mesmo?

2021-06-03 17:46 UTC, diegodsgarcia commented on packages/pilot/src/pages/Settlements/Filter/style.css
> +  margin-right: 16px;
`var(--spacing-small)`

2021-06-03 17:46 UTC, diegodsgarcia commented on packages/pilot/src/pages/Settlements/Filter/style.css
> +  margin-right: 16px;
`var(----spacing-small)`

2021-06-03 17:47 UTC, diegodsgarcia commented
Por fim não esquecer de fazer o `rebase` e resolver os conflitos que ocorreu com o ultimo merge na master

2021-06-04 13:08 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:08 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:08 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:08 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 13:09 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 15:05 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 15:05 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 15:05 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 15:05 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 15:19 UTC, Hrfreire commented
@LucasRichter não revisei a ultima vez ainda, mas precisa fazer o rebase com a branch de release pq tá dando conflito.

2021-06-04 16:37 UTC, Hrfreire commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +            dateLimit={moment().add('days', 7)}
```suggestion
            dateLimit={moment().add(7, 'days').endOf('day')}
```

Inverti a ordem dos argumentos, pq na forma que tá, é depracated no moment. E também adicionei o endOf('day') pra garantir que no último dia, vai funcionar até o final do dia. Tava ficando vermelho no último dia.

2021-06-04 17:03 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 423848b60b6676cc9ab0d8c1dfd5e01f6b2e7b1c
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 17:03 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9f293f032743d180f36d7342fcef26bdebc8cb83
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: a2c286e43043e729432e0ea0e6c00a1f2cb735a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: fb4277a86d7281509d279e3a7c3d23d6741d9f3a
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 6bf54b0409c06ee0c784be3ef09b19d2b229b9a2
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: de16d27957e57e7f960534bc6678851512e21ba9
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

 * Commit: 423848b60b6676cc9ab0d8c1dfd5e01f6b2e7b1c
  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2021-06-04 17:10 UTC, Hrfreire approved these changes

2021-06-04 18:46 UTC, rsmelo approved these changes

2021-06-04 19:05 UTC, merged

2021-06-04 19:08 UTC, SahBianchi commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +            dateLimit={moment().add(7, 'day').endOf('day')}
Acredito que seria legal documentar sobre esse raciocínio para ficar mais fácil para outras pessoas entenderem também, sobre o porque de mostrar mais 7 dias para frente.

2021-06-04 19:12 UTC, SahBianchi commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +/* eslint-disable react-hooks/rules-of-hooks */
Tem mesmo a necessidade de desabilitar o eslint?

2021-06-04 19:12 UTC, SahBianchi commented on packages/pilot/src/pages/Settlements/SettlementsPage.js
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Aqui também, tem a necessidade de desabilitar o eslint?

2021-06-04 19:13 UTC, SahBianchi commented on packages/pilot/src/pages/Settlements/tableColumns.js
> +/* eslint-disable react/prop-types */
Aqui também, tem a necessidade de desabilitar o eslint?